import os
import sys
import json

"""
Read in a json file and make it beautiful. This script primarily 
serves the JSON report generated by Magma#exp2json.py.
"""

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('python3 beautify_json.py <json_file>')
        exit(0)

    # Parse arg
    json_file = os.path.abspath(sys.argv[1])

    # Read json
    with open(json_file, 'r') as f:
        data = json.load(f)

    # Rewrite json
    with open(json_file, 'w') as f:
        json.dump(data, f, indent=2)
    print('[LOG] Finsh beautifying and rewriting', json_file)
